/**
 * This file is auto-generated by the supabase:types script.
 * Do not edit this file manually.
 */

/* eslint-disable */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      battle_order: {
        Row: {
          combatants: Json
          current_key: string | null
          mesa_id: string
          round: number
          started: boolean
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          combatants?: Json
          current_key?: string | null
          mesa_id: string
          round?: number
          started?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          combatants?: Json
          current_key?: string | null
          mesa_id?: string
          round?: number
          started?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "battle_order_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: true
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      custom_items: {
        Row: {
          created_at: string
          created_by: string | null
          description: string
          id: string
          mesa_id: string
          name: string
          one_use: boolean
          pocket: string
          price: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string
          id?: string
          mesa_id: string
          name: string
          one_use?: boolean
          pocket?: string
          price: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string
          id?: string
          mesa_id?: string
          name?: string
          one_use?: boolean
          pocket?: string
          price?: number
        }
        Relationships: [
          {
            foreignKeyName: "custom_items_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      day_pass_triggers: {
        Row: {
          mesa_id: string
          triggered_at: string | null
          triggered_by: string | null
        }
        Insert: {
          mesa_id: string
          triggered_at?: string | null
          triggered_by?: string | null
        }
        Update: {
          mesa_id?: string
          triggered_at?: string | null
          triggered_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "day_pass_triggers_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: true
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      item_gifts: {
        Row: {
          created_at: string
          from_user_id: string
          id: string
          item_id: string
          item_name: string
          mesa_id: string
          qty: number
          to_user_id: string
        }
        Insert: {
          created_at?: string
          from_user_id: string
          id?: string
          item_id: string
          item_name: string
          mesa_id: string
          qty: number
          to_user_id: string
        }
        Update: {
          created_at?: string
          from_user_id?: string
          id?: string
          item_id?: string
          item_name?: string
          mesa_id?: string
          qty?: number
          to_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_gifts_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      mesa_members: {
        Row: {
          joined_at: string
          mesa_id: string
          role: string
          user_id: string
        }
        Insert: {
          joined_at?: string
          mesa_id: string
          role?: string
          user_id: string
        }
        Update: {
          joined_at?: string
          mesa_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mesa_members_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      mesa_notes: {
        Row: {
          content: string
          mesa_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content?: string
          mesa_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: string
          mesa_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "mesa_notes_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: true
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      mesas: {
        Row: {
          capture_bonus_mode: string
          created_at: string
          id: string
          invite_code: string
          name: string
          owner_id: string
        }
        Insert: {
          capture_bonus_mode?: string
          created_at?: string
          id?: string
          invite_code?: string
          name: string
          owner_id: string
        }
        Update: {
          capture_bonus_mode?: string
          created_at?: string
          id?: string
          invite_code?: string
          name?: string
          owner_id?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          content: string
          created_at: string
          id: number
          kind: string
          mesa_id: string
          roll: Json | null
          user_id: string
        }
        Insert: {
          content?: string
          created_at?: string
          id?: never
          kind?: string
          mesa_id: string
          roll?: Json | null
          user_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: never
          kind?: string
          mesa_id?: string
          roll?: Json | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      money_adjustments: {
        Row: {
          amount: number
          created_at: string
          from_user_id: string
          id: string
          mesa_id: string
          to_user_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          from_user_id: string
          id?: string
          mesa_id: string
          to_user_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          from_user_id?: string
          id?: string
          mesa_id?: string
          to_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "money_adjustments_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      pokecenter_triggers: {
        Row: {
          mesa_id: string
          triggered_at: string | null
          triggered_by: string | null
        }
        Insert: {
          mesa_id: string
          triggered_at?: string | null
          triggered_by?: string | null
        }
        Update: {
          mesa_id?: string
          triggered_at?: string | null
          triggered_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pokecenter_triggers_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: true
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          id: string
          username: string
        }
        Insert: {
          created_at?: string
          id: string
          username: string
        }
        Update: {
          created_at?: string
          id?: string
          username?: string
        }
        Relationships: []
      }
      scout_rolls: {
        Row: {
          contributors: Json
          mesa_id: string
          total: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          contributors?: Json
          mesa_id: string
          total?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          contributors?: Json
          mesa_id?: string
          total?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "scout_rolls_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: true
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      session_notes: {
        Row: {
          content: string
          created_at: string
          created_by: string | null
          id: string
          mesa_id: string
          title: string
          updated_at: string
        }
        Insert: {
          content?: string
          created_at?: string
          created_by?: string | null
          id?: string
          mesa_id: string
          title: string
          updated_at?: string
        }
        Update: {
          content?: string
          created_at?: string
          created_by?: string | null
          id?: string
          mesa_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_notes_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      shared_sheets: {
        Row: {
          hidden: boolean
          id: string
          kind: string
          local_id: number
          mesa_id: string
          owner_id: string
          payload: Json
          updated_at: string
        }
        Insert: {
          hidden?: boolean
          id?: string
          kind: string
          local_id: number
          mesa_id: string
          owner_id: string
          payload: Json
          updated_at?: string
        }
        Update: {
          hidden?: boolean
          id?: string
          kind?: string
          local_id?: number
          mesa_id?: string
          owner_id?: string
          payload?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shared_sheets_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
      sheet_transfers: {
        Row: {
          created_at: string
          from_user_id: string
          id: string
          mesa_id: string
          payload: Json
          to_user_id: string
        }
        Insert: {
          created_at?: string
          from_user_id: string
          id?: string
          mesa_id: string
          payload: Json
          to_user_id: string
        }
        Update: {
          created_at?: string
          from_user_id?: string
          id?: string
          mesa_id?: string
          payload?: Json
          to_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sheet_transfers_mesa_id_fkey"
            columns: ["mesa_id"]
            isOneToOne: false
            referencedRelation: "mesas"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_mesa_gm: { Args: { _mesa: string }; Returns: boolean }
      is_mesa_member: { Args: { _mesa: string }; Returns: boolean }
      join_mesa: { Args: { _code: string }; Returns: string }
      roll_dice_shared: {
        Args: {
          _bonus?: number
          _icon?: string
          _label?: string
          _mesa_id: string
          _mode?: string
          _pool: number
          _sides?: number
        }
        Returns: Json
      }
      username_available: { Args: { _username: string }; Returns: boolean }
      whoami: { Args: never; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
